# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' bit_any
#'
#' Aggregate integer vector using bitwise or.
#'
#' @export
bit_any <- function(xs) {
    .Call(`_azwmisc_bit_any`, xs)
}

